site_name: Portfolio Site

theme:
    name: material
    custom_dir: overrides
    logo: assets/faceless_edit.png
    favicon: assets/faceless_edit.png
    palette:
        scheme: slate
        primary: black
        accent: orange
    features:
        - header.autohide
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky

markdown_extensions:
    - admonition
    - md_in_html
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite

nav:
    - Home: "index.md"
    - Portfolio:
          - Overview: "pages/portfolio/overview.md"
    - Resume:
          - Overview: "pages/resume/overview.md"
    - Contact: "contact.md"
