site_name: Hart Traveller
# repo_name: harttraveller.github.io
# repo_url: https://github.com/harttraveller/harttraveller.github.io

plugins:
- search
- roamlinks
- embed_file
- mkdocs-jupyter
- tags:
    tags_file: tags.md
- blog:
    blog_dir: work
    post_url_date_format: yyyy/MM/dd
    post_date_format: long
    draft_if_future_date: true
    categories_name: Type
    archive_name: Year


theme:
  name: material
  font:
    text: Inter
    code: Ubuntu Mono
  custom_dir: docs/overrides
  logo: assets/site/profile.png
  favicon: assets/site/profile.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - navigation.instant
  - navigation.tracking
  - content.code.copy
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.footer

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://www.github.com/harttraveller
  - icon: fontawesome/brands/gitlab
    link: https://www.gitlab.com/harttraveller
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/harttraveller/
  - icon: fontawesome/solid/envelope
    link: https://forms.gle/tazKaRH6pNENsCJK8

extra_css:
- stylesheets/extra.css

extra_javascript:
- "javascripts/extra.js"

markdown_extensions:
- attr_list
- md_in_html
- admonition
- footnotes
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
# - pymdownx.critic
- pymdownx.caret
# - pymdownx.keys
# - pymdownx.mark
- pymdownx.tilde
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Resume:
  - Overview: resume/index.md
  - Experience: resume/experience.md
  - Education: resume/education.md
- Work:
  - Index: work/index.md
- Tags: tags.md
