site_name: Hart Traveller
docs_dir: pages
site_url: https://harttraveller.com

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  # custom_dir: pages/assets/overrides
  palette:
    scheme: slate
    primary: custom
    accent: custom
  icon:
    annotation: material/plus-circle
  font:
    text: Inter
    code: Consolas
  features:
  - toc.follow
  - search.suggest
  - content.code.annotate
  - content.tabs.link
  - content.code.copy
  - navigation.top
  - navigation.tracking
  - navigation.indexes
  - navigation.expand
  - navigation.footer

plugins:
- search
- tags
- offline
- privacy
- markdown-exec
- awesome-nav
- roamlinks
- blog:
    blog_dir: .
# - callouts
# - embed_file:
#     callouts: true
# - autorefs
# - rss:
#     match_path: blog/posts/.*
#     date_from_meta:
#       as_creation: date
#     categories:
#     - categories
#     - tags

markdown_extensions:
- admonition
- attr_list
- footnotes
- md_in_html
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.superfences
- pymdownx.tilde
- pymdownx.snippets:
    base_path: [ "pages/scripts" ]
- toc:
    permalink: "#"
    title: Go To
- pymdownx.arithmatex:
    generic: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true

extra:
  generator: false

extra_css:
- assets/theme.css

extra_javascript:
- assets/javascripts/mathjax.js
- assets/javascripts/tex-mml-chtml.js

# - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# hooks: ...
