site_name: Hart Traveller
docs_dir: pages
site_url: https://harttraveller.github.io


nav:
- index.md

theme:
  name: material
  favicon: files/site/icon.png
  logo: files/site/icon.png
  logo_url: "/"
  logo_tooltip: ""
  custom_dir: pages/static/custom
  icon:
    annotation: material/plus-circle
  font:
    text: Inter
    code: Ubuntu Mono
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - search.suggest
  - content.code.copy
  - content.code.annotate
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky

plugins:
- search
- obsidian-bridge
# - mkdocs-jupyter
- glightbox
- git-revision-date-localized:
    enable_creation_date: true
- markmap:
    base_path: pages
    file_extension: .md
- blog:
    blog_dir: .
    blog_toc: true
    archive: true
    archive_name: Years
    archive_url_format: "year/{date}"
    archive_toc: true
    post_url_format: "{slug}"
    categories_url_format: "{slug}"
    pagination_per_page: 8
- rss:
    match_path: posts/.*
    comments_path: "#__comments"
    date_from_meta:
      as_creation: date
    categories:
    - categories


markdown_extensions:
- attr_list
- md_in_html
- admonition
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false
  quicklinks:
  # - name: Posts
  #   icon: lucide/pen
  #   type: link
  #   link: /post
  #   color: "#a86417"
  #   tooltip: true
  #   newtab: false
  # - name: Categories
  #   icon: lucide/tag
  #   type: link
  #   link: /post/categories
  #   color: "#a86417"
  #   tooltip: true
  #   newtab: false
  # - name: Archive
  #   icon: lucide/history
  #   type: link
  #   link: /post/archive
  #   color: "#a86417"
  #   tooltip: true
  #   newtab: false
  # - name: Tags
  #   icon: lucide/tag
  #   type: link
  #   link: ./tags
  #   color: "#a86417"
  #   tooltip: true
  #   newtab: false
  # - name: Projects
  #   icon: lucide/wrench
  #   type: link
  #   link: /projects
  #   color: "#a86417"
  #   tooltip: true
  #   newtab: false
  # - name: Resources
  #   icon: lucide/package
  #   type: link
  #   link: ./resources
  #   color: "#a86417"
  #   tooltip: true
  #   newtab: false
  # - name: Resume
  #   icon: lucide/briefcase
  #   type: link
  #   link: /resume
  #   color: "#a86417"
  #   tooltip: true
  #   newtab: false
  # - name: RSS
  #   icon: lucide/rss
  #   type: copy
  #   text: https://harttraveller.com/feed_rss_created.xml
  #   color: darkred
  #   tooltip: true
  - name: Email
    icon: lucide/mail
    type: copy
    text: ruling_fiction.0b@icloud.com
    color: darkred
    tooltip: true
    # - name: GitHub
    #   icon: lucide/github
    #   type: link
    #   link: https://github.com/harttraveller
    #   color: rgb(30, 70, 160)
    #   tooltip: true
    #   newtab: true
    # - name: GitLab
    #   icon: lucide/gitlab
    #   type: link
    #   link: https://www.gitlab.com/harttraveller
    #   color: rgb(30, 70, 160)
    #   tooltip: true
    #   newtab: true
    # - name: PyPi
    #   icon: logo/python
    #   type: link
    #   link: https://pypi.org/user/harttraveller/
    #   color: rgb(30, 70, 160)
    #   tooltip: true
    #   newtab: true
    # - name: LinkedIn
    #   icon: lucide/linkedin
    #   type: link
    #   link: https://www.linkedin.com/in/harttraveller/
    #   color: rgb(30, 70, 160)
    #   tooltip: true
    #   newtab: true
    # - name: Cephalon Intelligence
    #   icon: lucide/eye
    #   type: link
    #   link: https://cephalon.io
    # - name: AI Chat
    #   icon: lucide/bot
    #   link: https://ai.harttraveller.com
    #   color: rgb(30, 70, 160)
    # - name: Brain
    #   icon: lucide/brain-circuit
    #   link: https://brain.harttraveller.com
    #   color: rgb(30, 70, 160)
    # dagshub, huggingface

extra_css:
- static/styles/global.theme.css
- static/styles/global.markmap.css
- static/styles/max.theme.css
- static/styles/global.admonition.css
- static/styles/global.notebook.css
- static/styles/med.theme.css
- static/styles/min.theme.css
- static/styles/testing.css

extra_javascript:
- static/scripts/extra.js
- static/scripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


