site_name: Hart Traveller
docs_dir: pages
site_url: https://harttraveller.com

theme:
  name: material
  # logo: ...
  # favicon: ...
  custom_dir: pages/assets/overrides
  palette:
    scheme: slate
    primary: custom
    accent: custom
  icon:
    annotation: material/plus-circle
  font:
    text: Inter
    code: Consolas
  features:
  - toc.follow
  - search.suggest
  - content.code.annotate
  - content.tabs.link
  - content.code.copy
  - navigation.top
  - navigation.footer
  - navigation.tracking
  - navigation.indexes

plugins:
- search
- blog
- tags
- offline
- privacy
- markdown-exec
- awesome-nav
# - callouts
# - embed_file:
#     callouts: true
# - autorefs
# - roamlinks

markdown_extensions:
- admonition
- attr_list
- footnotes
- md_in_html
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tilde
- toc:
    permalink: "#"
    title: Go To
- pymdownx.arithmatex:
    generic: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true

extra:
  generator: false

extra_css:
- assets/theme.css

# extra_javascript:
#   - assets/javascripts/mathjax.js
#   - assets/javascripts/tex-mml-chtml.js

# hooks: ...
