site_name: Hart Traveller
docs_dir: pages
site_url: harttraveller.com

theme:
  name: material
  palette:
    scheme: slate
  icon:
    annotation: material/plus-circle
  features:
  - toc.follow
  - search.suggest
  - content.code.annotate
  - content.tabs.link
  - content.code.copy
  - navigation.top
  - navigation.footer
  - navigation.tracking
  - navigation.indexes

plugins:
- search
- blog
- tags
- offline

extra:
  generator: false

markdown_extensions:
- admonition
- attr_list
- footnotes
- md_in_html
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tilde

nav:
- Home: "index.md"
